swagger: "2.0"
info:
  version: 1.0.0
  title: ICS API Ver 1.0
  description: Api Sample for to ICS HLF Framework
basePath: /api/v1
tags:
  - name: Product
    description: Product
  - name: Delivery
    description: Delivery
  - name: Examples
    description: Simple example endpoints
  - name: Balance
    description: Simple Balance Transfer Example
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  product:
    required:
    - dstrb_id
    - seq
    - lat
    - lng
    - full_addr
    - prv_nm
    - city_nm
    - dstr_nm
    - dv_id
    - dstrb_typ_cd
    - dstrb_typ_nm
    - corp_id
    - corp_nm
    - corp_user_id
    - corp_user_nm
    - prod_nm
    - rgst_dtm
    properties:
      dstrb_id:
        type: string
      seq:
        type: string
      lat:
        type: string
      lng:
        type: string
      full_addr:
        type: string
      prv_nm:
        type: string
      city_nm:
        type: string
      dstr_nm:
        type: string
      dv_id:
        type: string
      dstrb_typ_cd:
        type: string
      dstrb_typ_nm:
        type: string
      corp_id:
        type: string
      corp_nm:
        type: string
      corp_user_id:
        type: string
      corp_user_nm:
        type: string
      prod_nm:
        type: string
      rgst_dtm:
        type: string

  delivery:
    required:
    - dv_id
    - dv_dtm
    - corp_id
    - corp_nm
    - lat
    - lng
    - corp_user_id
    - corp_user_nm
    properties:
      dv_id:
        type: string
      dv_dtm:
        type: string
      corp_id:
        type: string
      corp_nm:
        type: string
      lat:
        type: string
      lng:
        type: string
      corp_user_id:
        type: string
      corp_user_nm:
        type: string

  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  move:
    required:
    - from
    - to
    - amount
    properties:
      from:
        type: string
      to:
        type: string
      amount:
        type: integer

  user:
    required:
    - name
    - balance
    properties:
      name:
        type: string
      balance:
        type: integer

paths:
  /product/{id}/:
    get:
      tags:
      - Product
      parameters:
      - name: id
        in: path
        required: true
        description: 상품 seq ex) 9
        type: string
      description: 상품정보 조회
      responses:
        200:
          description: Returns Product Change History

  /product:
    post:
      tags:
      - Product
      parameters:
      - name: example
        in: body
        required: true
        description: Product Info For Regist Blockchain
        schema:
          $ref: "#/definitions/product"
      description: Regist Product information
      responses:
        200:
          description: Returns like success/fail code
  /delivery/{id}/:
    get:
      tags:
      - Delivery
      parameters:
      - name: id
        in: path
        required: true
        description: query delivery dv_id
        type: string
      description: Get Delivery Info
      responses:
        200:
          description: Returns Delivery History

  /delivery:
    post:
      tags:
      - Delivery
      parameters:
      - name: id
        in: body
        required: true
        schema:
          $ref: "#/definitions/delivery"
      description: The id of the user to be added
      responses:
        200:
          description: Returns User's Current Balance

  /balance/saveUser:
    post:
      tags:
      - Balance
      description: Fetch all examples
      parameters:
      - name: Channel
        in: query
        type: string
        description: an example
        required: true
      - name: Id
        in: query
        type: string
        description: an example
        required: true
      - name: Name
        in: query
        type: string
        description: an example
        required: true
      - name: Age
        in: query
        type: string
        description: an example
        required: true
      - name: Sex
        in: query
        type: string
        description: an example
        required: true
      responses:
        200:
          description: Returns all examples

  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /balance/{id}:
    get:
      tags:
      - Balance
      parameters:
      - name: id
        in: path
        required: true
        description: The id of the user to retrieve currently balance
        type: string
      description: Get User Balance
      responses:
        200:
          description: Returns User's Currently Balance

  /balance/user:
    post:
      tags:
      - Balance
      parameters:
      - name: id
        in: body
        required: true
        schema:
          $ref: "#/definitions/user"
      description: The id of the user to be added
      responses:
        200:
          description: Returns User's Current Balance

  /balance:
    post:
      tags:
      - Balance
      parameters:
      - name: move balance request
        in: body
        description: The id of the user to retrieve currently balance
        required: true
        schema:
          $ref: "#/definitions/move"
      description: Get User Balance
      responses:
        200:
          description: Returns User's Currently Balance

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
